language: node_js
node_js:
  - "8"
cache: npm
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - npm install
  - echo 'linting check'
install:
  - npm install -g firebase-tools
after_success:
  - npm run build
  - npm run deploy